#!/bin/bash

set -e

unamestr=`uname`
if [[ "$unamestr" == 'Linux' ]]; then
  sudo apt update && sudo apt upgrade -y
elif [[ "$unamestr" == 'Darwin' ]]; then
  brew upgrade
fi

npm update -g

cd ~/.vim && git remote update && git rebase origin/master master && cd -

cd ~/configurations/ && git remote update && git rebase origin/master master && cd -

~/.tmux/plugins/tpm/bin/update_plugins all

vim +PlugUpdate +PlugUpgrade +qa

dasht-docsets-update

set +e
