#!/bin/bash

set -e

unamestr=`uname`
if [[ "$unamestr" == 'Linux' ]]; then
  sudo apt update && sudo apt upgrade -y
elif [[ "$unamestr" == 'Darwin' ]]; then
  brew upgrade
fi

if command -v npm &> /dev/null; then
  npm update -g
fi

cd ~/.vim && git remote update && git rebase origin/master master && cd -

cd ~/configurations/ && git remote update && git rebase origin/master master && cd -

~/.tmux/plugins/tpm/bin/update_plugins all

# Upgrade pip packages
# pip install --upgrade powerline-shell

vim +PlugUpdate +PlugUpgrade +qa

if command -v dasht-docsets-update &> /dev/null; then
  dasht-docsets-update
fi

set +e
